Add certifications for MP 7.0
OpenLiberty/certifications pull request #313
Opened 2024-12-03 14:31 UTC by benjamin-confino

Adds certifications for MP70 on 24.0.0.12.

Link to draft site: https://certifications-draft-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/certifications/microprofile/7.0/24.0.0.12-TCKResults.html

2024-12-05 14:39 UTC, Emily-Jiang commented on microprofile/7.0/24.0.0.12-TCKResults.adoc
> +MicroProfile 7.0 consists of 8 MicroProfile Specifications plus the Jakarta EE Core Profile 10.0 specfication.
```suggestion
MicroProfile 7.0 consists of 7 MicroProfile Specifications and it depends on the Jakarta EE Core Profile 10.0 specfication.
```

2024-12-05 14:47 UTC, Emily-Jiang requested changes
The links to the spec and download url should point to the maven central instead of the github repo. e.g. 

https://repo1.maven.org/maven2/org/eclipse/microprofile/fault-tolerance/microprofile-fault-tolerance-spec/4.1/

2024-12-09 09:45 UTC, Emily-Jiang commented on microprofile/7.0/telemetry/2.0/24.0.0.12-MicroProfile-Telemetry-2.0-Java11-TCKResults.adoc
> +https://repo1.maven.org/maven2/org/eclipse/microprofile/telemetry/microprofile-telemetry-logs-tck/2.0-RC2/microprofile-telemetry-logs-tck-2.0-RC2.jar[MicroProfile Telemetry 2.0 Logs TCK]
These are RC not the final jar.

2024-12-09 09:45 UTC, Emily-Jiang commented on microprofile/7.0/telemetry/2.0/24.0.0.12-MicroProfile-Telemetry-2.0-Java11-TCKResults.adoc
> +https://repo1.maven.org/maven2/org/eclipse/microprofile/telemetry/microprofile-telemetry-metrics-tck/2.0-RC2/microprofile-telemetry-metrics-tck-2.0-RC2.jar[MicroProfile Telemetry 2.0 Metrics TCK]
These is the RC not the final jar.

2024-12-09 09:45 UTC, Emily-Jiang commented on microprofile/7.0/telemetry/2.0/24.0.0.12-MicroProfile-Telemetry-2.0-Java11-TCKResults.adoc
> +https://repo1.maven.org/maven2/org/eclipse/microprofile/telemetry/microprofile-telemetry-tracing-tck/2.0-RC2/microprofile-telemetry-tracing-tck-2.0-RC2.jar[MicroProfile Telemetry 2.0 Tracing TCK]
These is the RC not the final jar.

2024-12-09 09:47 UTC, Emily-Jiang commented on microprofile/7.0/telemetry/2.0/24.0.0.12-MicroProfile-Telemetry-2.0-Java11-TCKResults.adoc
> +https://repo1.maven.org/maven2/org/eclipse/microprofile/telemetry/microprofile-telemetry-metrics-tck/2.0-RC2/microprofile-telemetry-metrics-tck-2.0-RC2.jar[MicroProfile Telemetry 2.0 Metrics TCK]
please make corrections for all Java levels.

2024-12-10 09:02 UTC, Emily-Jiang commented on microprofile/7.0/24.0.0.12-TCKResults.adoc
> +* xref:faulttolerance/4.1/24.0.0.12-MicroProfile-Fault-Tolerance-4.1-Java11-TCKResults.adoc[MicroProfile Fault Tolerance 4.1 TCK Result (Java 11)]
wrong link

2024-12-10 09:02 UTC, Emily-Jiang commented on microprofile/7.0/24.0.0.12-TCKResults.adoc
> +* xref:telemetry/2.0/24.0.0.12-MicroProfile-Telemetry-2.0-Java11-TCKResults.adoc[MicroProfile Telemetry 2.0 TCK Result (Java 11)]
broken link

2024-12-10 09:03 UTC, Emily-Jiang commented
@benjamin-confino you made the changes but did not change the links. You need to update the links for all java versions.

2024-12-11 13:34 UTC, Emily-Jiang approved these changes

2024-12-11 17:53 UTC, ayoho approved these changes

2024-12-11 17:53 UTC, merged